parameters:
    supertag_gearman.client.class: Supertag\Bundle\GearmanBundle\Client

services:
    supertag_gearman.client:
        class: %supertag_gearman.client.class%
        arguments: [ %supertag_gearman.servers%, %supertag_gearman.namespace% ]

